### ISSUE TITLE
 Google Form Design for Record Clearance

### ISSUE THREAD

**Issue by j100892** [hackforla/record-clearance#113]
### Overview

> Please ask whoever is the designer on the Record Clearance project to make a header for the form .  Here is an example of some standard hack for LA form headers for various projects https://github.com/hackforla/product-managment/issues/23. If the designer designs one that can accommodate stake holder logos when we use it with them to test, that would be good.

### Action Items

- [x] Assign Task to Designer
- [x] Create Designs 
- [x] Integrate with our Current Form 
- [x] Share with Bonnie 

### Resources/Instructions

**Our Current Form:** 

- https://docs.google.com/forms/d/e/1FAIpQLSfq53fzh1Y8d5x0hhn3PDFBvV5CGFAiMDHuqr9T7xCiPVQ7iQ/viewform 

**Reference this issue to replicate the customer header:**

-  https://github.com/hackforla/product-managment/issues/23

**Comment by j100892** [comment]
Assigned to Tina M. for custom illustrations. Pending her response on her github handle: tina-moh @ExperimentsInHonesty

**Comment by tina-moh** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSfq53fzh1Y8d5x0hhn3PDFBvV5CGFAiMDHuqr9T7xCiPVQ7iQ/viewform

**Comment by tina-moh** [comment]
[](url)
![image](https://user-images.githubusercontent.com/56663382/108009427-89692600-6fb7-11eb-999e-7da703fcb22d.png)
