### ISSUE TITLE
More Robust Google Form Survey 

### ISSUE THREAD

**Issue by j100892** [hackforla/record-clearance#137]
### Overview

Can something replace the current Google Form we are using to test generating personal statements? 

### Action Items

Look into Substack and how it could fit in with our current contet 

### Resources/Instructions

https://formstack.com/

https://www.qualtrics.com/

**Comment by kande81** [comment]
@j100892 i think the site is actually formstack.com

**Comment by j100892** [comment]
Update @myrandi and @kande81 to look into a Qualtrics survey option to replace the Google Form survey in the future. We need more complex conditionals and mirroring the current designs of the generator through the survey which is limited by the current Google Form version. 

I'm still going to be looking to build out a decision tree with the current Google Form in the meantime.

**Comment by myrandi** [comment]
Qualtrics [survey](https://bostonu.qualtrics.com/jfe/form/SV_2fsXelfddwk1rzE) (draft)

**Comment by myrandi** [comment]
Gilles built [survey](https://recordclearanceproject.formstack.com/forms/record_clearance_statement_generator
) using Formstack

[Answers](https://www.formstack.com/admin/submission/report/26615408?page=1&share=mSh9s98gzn) on fs 

Google sheet [responses](https://docs.google.com/spreadsheets/d/16_jczxzjdd-nr6dxt8M4PKdpxSCePzcg/edit?usp=drive_web&ouid=109979492177025079714&rtpof=true):

**Comment by myrandi** [comment]
Update: shared with Bonnie Wed January 20th

Status: waiting for Bonnie to connect with us to go over sequencing and output

**Comment by ggrrettcchhenn** [comment]
Update: Thinking of moving forward with Jotform, which is [free up to 5 surveys](https://www.jotform.com/pricing/) and has a [Google Sheets integration](https://www.jotform.com/help/228-how-to-integrate-forms-with-google-sheets) that we can use to automatically store responses in Google Sheets. The formulas created in Sheets can generate the statements. We can share the statements tab with Bo, and use the Jotform to conduct user testing on our statement generator.

**Comment by myrandi** [comment]
> Update: Thinking of moving forward with Jotform, which is [free up to 5 surveys](https://www.jotform.com/pricing/) and has a [Google Sheets integration](https://www.jotform.com/help/228-how-to-integrate-forms-with-google-sheets) that we can use to automatically store responses in Google Sheets. The formulas created in Sheets can generate the statements. We can share the statements tab with Bo, and use the Jotform to conduct user testing on our statement generator.

> This should work. Qualtrics can be a backup in case we run out of space or needs exceed functionality/logic, but Jotform is more sustainable as an open/free program.

**Comment by ggrrettcchhenn** [comment]
Made JotForm here: https://form.jotform.com/210456150734146
It exports the answers to this Sheet: https://docs.google.com/spreadsheets/d/1o1iHthALkwtvptA-NevAZUDgRb7f4kCxr-rTSr9Z0Ek/edit?usp=sharing

I still need to figure out how to get the formula working properly -- I copied it over from this sheet: https://docs.google.com/spreadsheets/d/1Z_EDT1zRV_0oKjRGgOYQA5RWs7C1NhYWVTqdFyy_Nx0/edit?usp=sharing
