### ISSUE TITLE
add automation to publish built app to gh-pages

### ISSUE THREAD

**Issue by jafow** [hackforla/record-clearance#46]
# todo

when PR is merged to `main` branch an action will build and put into a directory on the gh-pages branch so that the app is published toa github pages page.

**Comment by alexchoiweb** [comment]
After some noodling we have deployment to a github pages page from the `dev` branch:

https://hackforla.github.io/record-clearance/#/

Let me know if this is not the way
Will continue to work on the automated CI aspect later this week

Resources followed for anyone who would like to recreate:
[Setting up (only used 1st half of article up to router issues)](https://itnext.io/so-you-want-to-host-your-single-age-react-app-on-github-pages-a826ab01e48)
[Fixing github pages not playing well with react-router](https://youtu.be/1wDzEjXbblM?t=253)

**Comment by alexchoiweb** [comment]
Actually I decided to go back to BrowserRouter using [this solution ](https://github.com/rafgraph/spa-github-pages)
All links work appropriately on github pages now - [link](https://hackforla.github.io/record-clearance/)

automated CI is still on the to do list for this week

**Comment by alexchoiweb** [comment]
CICD is now set up - master branch will deploy client build to project's [github page]( https://hackforla.github.io/record-clearance/) on push or merge
Note: It takes about 30seconds for the github page to update (try hard refreshes) after the Action is completed.

Big thanks to @jafow for the help!

References: [Github Action for setup](https://github.com/marketplace/actions/publish-to-github-pages)
