### ISSUE TITLE
Research Summary - CA Crime Stat's

### ISSUE THREAD

**Issue by H1Angela** [hackforla/record-clearance#5]
### Overview
Given the amount of data available we need a summary of the CA Crime Stat's document and research on the record clearance project. 

### Action Items
Review the following doc:
- [ ] CA Crime Stat's

### Resources/Instructions
[The Google drive link](https://drive.google.com/drive/u/0/folders/1hBhOeNyjjEaHcWAKSu9eW--FF9HnKNqe)

[Work will be put here](https://docs.google.com/document/d/1oUgN7vT0M-nkMBj68ugPOvvZSgngkL8aRMfX2zF9olk/edit?usp=sharing)

**Comment by saintpf** [comment]
document has been reviewed.
summary was added to the google doc.

https://docs.google.com/document/d/1oUgN7vT0M-nkMBj68ugPOvvZSgngkL8aRMfX2zF9olk/edit#heading=h.ijrwwm3mjt93
