### ISSUE TITLE
Make single line input component

### ISSUE THREAD

**Issue by cayd** [hackforla/record-clearance#52]
### Overview
Build a single line entry component for input

### Action Items
Create a JSX component that takes as its input a type for an input value and a string for a prompt. 

### Resources/Instructions
Re: wireframe 3, date - name - age components
React, Material, clearmyrecord site

**Comment by jfowler-imb** [comment]
https://www.figma.com/file/t1lW4Tm0Lp3jFdeOCd98b1/Record-Clearance-Personal-Statement?node-id=0%3A1

**Comment by jfowler-imb** [comment]
https://material-ui.com/components/text-fields/
