### ISSUE TITLE
Google Drive Cleanup

### ISSUE THREAD

**Issue by j100892** [hackforla/record-clearance#54]
### Overview

Current drive needs a separate folder with a consistent naming structure so new volunteers can easily reference research and documents most relevant to the personal statement generator work. 

### Action Items

Format should be as follows: Date_Title_Initials(if applicable)_Version(if applicable)

### Resources/Instructions

Import files to this folder: 

[Google drive folder](https://drive.google.com/drive/folders/1oYfLSlWZNZ4ezpNJV2N1eXnC_nDcQ0QX?usp=sharing/)

**Assigned to Tierney and Gyan**

**Comment by myrandi** [comment]
Daniel - is the Google Drive link supposed to be active? Looks like I need access so wondering if it is supposed to be a different drive link

Let's go over folder organizing at the next Tues design meeting so we can all decide together how we should do it before I move everything to somewhere nobody can find it!

**Comment by j100892** [comment]
@myrandi Sorry, we made a new Google Drive from the old team one. I think I accidentally linked the old team's Google Drive in the ticket. I updated it with the Google Drive that has recordclearance@hackforla.org as the owner which you've had access to and have been working on. You can move around files, add to it and organize it.

**Comment by myrandi** [comment]
Cleaned up drive; research organized by subject; archived based on date (years: 2019 - present)
