### ISSUE TITLE
Onboard More Engineers 

### ISSUE THREAD

**Issue by j100892** [hackforla/record-clearance#70]
### Overview
Finding more developers to help with personal statement generator efforts

**Comment by j100892** [comment]
Wanted to note in case this is news - Cade was gracious enough to let us switch to Typescript for this app, it's not terribly hard to pick up if you have good control of javascript, but future frontend should be aware of this

**Comment by alexchoiweb** [comment]
Wanted to note in case this is news - Cade was gracious enough to let us switch to Typescript for this app, it's not terribly hard to pick up if you have good control of javascript, but future frontend should be aware of this
