### ISSUE TITLE
FAQ Designs 

### ISSUE THREAD

**Issue by j100892** [hackforla/record-clearance#79]
**Gilles is also on this ticket**

### Overview
Need designs for an FAQ section on the landing page that is responsive from desktop to mobile. 
### Action Items
Content should provide information to users that they could be potentially eligible to reduce their felonies through prop 47 and prop 64.

**Comment by alexchoiweb** [comment]
Hey all, wondering how I can help here, perhaps I was assigned accidentally?

**Comment by j100892** [comment]
@alexchoiweb Mostly wanted you to be aware that there were additional designs +content/copy coming for the landing page. They're not major but might take the form of an expandable row or infinite scroll type of action with content.
