### ISSUE TITLE
Questions to ask Code for America Staff 

### ISSUE THREAD

**Issue by j100892** [hackforla/record-clearance#95]
### Overview
Code for America is hosting a workshop series and a separate office hours session to answer any questions we might have. 

### Action Items
We need to review our past research and come with a set of questions that will help us better 

- Collaborate with the Clear My Record Program team 

- Network for partnerships with organizations that they feel would be a good fit

- Questions on additional work we can do in the justice impacted individuals space 

- Any feedback they have on the personal statement generator

**Comment by myrandi** [comment]
Added to Google [drive:](https://docs.google.com/document/d/11mxrn7hmGhl7ndLf5o3bBkeICAbl6KknpIh8g-QC_qs/edit?usp=sharing)
Record Clearance Project > Personal Statement Generator > User Research > Interview & Question Guides
